package com.showback.dto;

import lombok.Data;

import java.time.LocalDateTime;

@Data
public class ReviewDTO {

    private Long reviewId;

    private int reviewGrade;

    private String reviewText;

    private LocalDateTime reviewTimestamp;

    private Long showId;

    private Long authId;

    private String token;

    // Constructors, getters, setters (can be generated by Lombok)
}
