package com.showback.dto;

import lombok.Data;

@Data
public class ReviewDTO {

    private Long reviewId;

    private int reviewGrade;

    private String reviewText;

    private String reviewImgUrl;

    private Long showId;

    // Constructors, getters, setters (can be generated by Lombok)
}
