package com.showback.dto;

import lombok.Data;

@Data
public class ShowBannerDTO {

    private Long showBannerId;

    private String bannerUrl;

    private String smallBannerUrl;

    private Long showId;

    // Constructors, getters, setters (can be generated by Lombok)
}
