package com.showback.dto;

import lombok.Data;

import java.util.Date;

@Data
public class ShowScheduleDTO {

    private Long scheduleId;

    private Date scheduleDate;

    private Date scheduleTime;

    private Long showId;

    // Constructors, getters, setters (can be generated by Lombok)
}
